// Generated by scripts/optimize-media.mjs. Edit slot mapping and focal points there, then rerun.
export type MediaAsset = {kind: 'image' | 'video' | 'placeholder';src:string;srcset:{width:number;avif:string;webp:string}[];sources:{src:string;type:string;width:number;height:number;bytes:number;mobile:boolean}[];poster:string;blurDataURL:string;focal:{x:number;y:number};alt:string;credit:string;stock:boolean;width:number;height:number;scrimStrength?:number};
const base = (process.env.NEXT_PUBLIC_MEDIA_BASE_URL ?? '').replace(/\/$/, '');
const url = (src:string) => {const encoded=src.split('/').map(encodeURIComponent).join('/');return src.startsWith('/media/') && base ? base + encoded : encoded;};
const assets: Record<string,MediaAsset> = {
  "video:12966194_4096_2160_25fps": {
    "kind": "video",
    "src": "/media/images/12966194_4096_2160_25fps-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/12966194_4096_2160_25fps-poster-640.avif",
        "webp": "/media/images/12966194_4096_2160_25fps-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/12966194_4096_2160_25fps-poster-1080.avif",
        "webp": "/media/images/12966194_4096_2160_25fps-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/12966194_4096_2160_25fps-poster-1920.avif",
        "webp": "/media/images/12966194_4096_2160_25fps-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/12966194_4096_2160_25fps-poster-2560.avif",
        "webp": "/media/images/12966194_4096_2160_25fps-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/12966194_4096_2160_25fps-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 566762,
        "mobile": true
      }
    ],
    "poster": "/media/images/12966194_4096_2160_25fps-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoYAA0APxFysFAsJqSisAgBgCIJaQAAKvUB2g05eKHQAAD9YxT1iGQA9MzZJI0hFXJ88PJS4M0wYk/JuMijDP8JeP4QAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Black-and-white industrial processing equipment and piping",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 4096,
    "height": 2160,
    "scrimStrength": 0.81
  },
  "video:14529100_3840_2160_30fps": {
    "kind": "video",
    "src": "/media/images/14529100_3840_2160_30fps-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/14529100_3840_2160_30fps-poster-640.avif",
        "webp": "/media/images/14529100_3840_2160_30fps-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/14529100_3840_2160_30fps-poster-1080.avif",
        "webp": "/media/images/14529100_3840_2160_30fps-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/14529100_3840_2160_30fps-poster-1920.avif",
        "webp": "/media/images/14529100_3840_2160_30fps-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/14529100_3840_2160_30fps-poster-2560.avif",
        "webp": "/media/images/14529100_3840_2160_30fps-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/14529100_3840_2160_30fps-1080.mp4",
        "type": "video/mp4",
        "width": 1920,
        "height": 1080,
        "bytes": 1370149,
        "mobile": false
      },
      {
        "src": "/media/videos/14529100_3840_2160_30fps-1080-vp9.webm",
        "type": "video/webm",
        "width": 1920,
        "height": 1080,
        "bytes": 2472831,
        "mobile": false
      },
      {
        "src": "/media/videos/14529100_3840_2160_30fps-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 355795,
        "mobile": true
      }
    ],
    "poster": "/media/images/14529100_3840_2160_30fps-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoYAA4APxF2sVAsJ6SisAgBgCIJQBOmUGXShkdZ/YSOWJAAAPBvvmAHRotCbiw5QsX2dXncnalwB8xa06LfQW9+1QMMS/xBNKl7UCcizsbQAAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Offshore platform and vessel at sunset",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3840,
    "height": 2160,
    "scrimStrength": 0.77
  },
  "video:15122253_2160_3840_30fps": {
    "kind": "video",
    "src": "/media/images/15122253_2160_3840_30fps-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/15122253_2160_3840_30fps-poster-640.avif",
        "webp": "/media/images/15122253_2160_3840_30fps-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/15122253_2160_3840_30fps-poster-1080.avif",
        "webp": "/media/images/15122253_2160_3840_30fps-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/15122253_2160_3840_30fps-poster-1920.avif",
        "webp": "/media/images/15122253_2160_3840_30fps-poster-1920.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/15122253_2160_3840_30fps-720.mp4",
        "type": "video/mp4",
        "width": 406,
        "height": 720,
        "bytes": 275337,
        "mobile": true
      }
    ],
    "poster": "/media/images/15122253_2160_3840_30fps-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADwAQCdASoJABAABABoJZACdADcH7gxQAAA934wTi6xr1iyuP960rNJUk6Gt87TsE1sq9M/AAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Portrait clip of a worker among industrial pipes",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 2160,
    "height": 3840,
    "scrimStrength": 0.83
  },
  "video:4392869-uhd_3840_2160_30fps": {
    "kind": "video",
    "src": "/media/images/4392869-uhd_3840_2160_30fps-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/4392869-uhd_3840_2160_30fps-poster-640.avif",
        "webp": "/media/images/4392869-uhd_3840_2160_30fps-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/4392869-uhd_3840_2160_30fps-poster-1080.avif",
        "webp": "/media/images/4392869-uhd_3840_2160_30fps-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/4392869-uhd_3840_2160_30fps-poster-1920.avif",
        "webp": "/media/images/4392869-uhd_3840_2160_30fps-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/4392869-uhd_3840_2160_30fps-poster-2560.avif",
        "webp": "/media/images/4392869-uhd_3840_2160_30fps-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/4392869-uhd_3840_2160_30fps-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 255105,
        "mobile": true
      }
    ],
    "poster": "/media/images/4392869-uhd_3840_2160_30fps-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoYAA4APxF4tFGsJyUisAgBgCIJZQAAW+sAeKcqeFinbAD+3nY3FPMOH2wChzvMhKZZLtz2spygC4YVLDQAAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Crane vessel at an offshore worksite",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3840,
    "height": 2160,
    "scrimStrength": 0.82
  },
  "video:9339478-uhd_3840_2160_24fps": {
    "kind": "video",
    "src": "/media/images/9339478-uhd_3840_2160_24fps-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/9339478-uhd_3840_2160_24fps-poster-640.avif",
        "webp": "/media/images/9339478-uhd_3840_2160_24fps-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/9339478-uhd_3840_2160_24fps-poster-1080.avif",
        "webp": "/media/images/9339478-uhd_3840_2160_24fps-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/9339478-uhd_3840_2160_24fps-poster-1920.avif",
        "webp": "/media/images/9339478-uhd_3840_2160_24fps-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/9339478-uhd_3840_2160_24fps-poster-2560.avif",
        "webp": "/media/images/9339478-uhd_3840_2160_24fps-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/9339478-uhd_3840_2160_24fps-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 822155,
        "mobile": true
      }
    ],
    "poster": "/media/images/9339478-uhd_3840_2160_24fps-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQBACdASoYAA4APxF0sVAsJySisAgBgCIJZwDA3CHZmvHU6R8d6/uSoAD+w0NoCv/590slDagvCKs3S6l8oyG9cISaEJFk8IAaQACzgAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Daytime aerial view of refinery processing units",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3840,
    "height": 2160,
    "scrimStrength": 0.83
  },
  "image:Electrical & Instrumentation": {
    "kind": "image",
    "src": "/media/images/Electrical & Instrumentation-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/Electrical & Instrumentation-640.avif",
        "webp": "/media/images/Electrical & Instrumentation-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/Electrical & Instrumentation-1080.avif",
        "webp": "/media/images/Electrical & Instrumentation-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/Electrical & Instrumentation-1920.avif",
        "webp": "/media/images/Electrical & Instrumentation-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/Electrical & Instrumentation-2560.avif",
        "webp": "/media/images/Electrical & Instrumentation-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/Electrical & Instrumentation-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoYABAAPxF0sFCsJqSisAgBgCIJZwAAP8VIYECOFWU/l/AA/qm4C2E1mrXoA0YeHyTq1vXt3icV+FIbLrp5gYTujyLd7vek/phiqR8nvZFtDp+BLHFSPts9nDS66foOFbgybAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Electrical control-panel wiring and instrumentation",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 6000,
    "height": 4000,
    "scrimStrength": 0.84
  },
  "image:Procurement-supply-chain": {
    "kind": "image",
    "src": "/media/images/Procurement-supply-chain-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/Procurement-supply-chain-640.avif",
        "webp": "/media/images/Procurement-supply-chain-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/Procurement-supply-chain-1080.avif",
        "webp": "/media/images/Procurement-supply-chain-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/Procurement-supply-chain-1920.avif",
        "webp": "/media/images/Procurement-supply-chain-1920.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/Procurement-supply-chain-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoNABAABABoJQBYdiHesZ6k9AAA/uGEiYgE3LVSR7xkJ5AJjz3l6FSMLsaMyaEOYBEJdZgAAAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Container vessel illustrating procurement and supply chains",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 2462,
    "height": 3078,
    "scrimStrength": 0.81
  },
  "image:Sectors": {
    "kind": "image",
    "src": "/media/images/Sectors-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/Sectors-640.avif",
        "webp": "/media/images/Sectors-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/Sectors-1080.avif",
        "webp": "/media/images/Sectors-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/Sectors-1920.avif",
        "webp": "/media/images/Sectors-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/Sectors-2560.avif",
        "webp": "/media/images/Sectors-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/Sectors-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoYAA4APxF8tFGsKCUisAgBgCIJQBOmUGP2iUBzfXY6oyI3CgAA/iDbpUa30P/yGhh8lwM1PCS7nuAJ+GnJBxsTyC9kAkQ25K6vwld68AA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Offshore structures at sunset",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 5978,
    "height": 3370,
    "scrimStrength": 0.75
  },
  "image:alex-kotliarskyi-QBpZGqEMsKg-unsplash": {
    "kind": "image",
    "src": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-640.avif",
        "webp": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-1080.avif",
        "webp": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-1920.avif",
        "webp": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-2560.avif",
        "webp": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoYABAAPxFysFAsJqSisAgBgCIJZwDKAAyvHUimXnJ3bCAA/uj/QycWdOGrrAdZtCEocuUxWrRmsBQnPFLtFsi26MIY/tQt2KZxd9/PmlzqAAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "alex kotliarskyi QBpZGqEMsKg unsplash",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 5472,
    "height": 3648,
    "scrimStrength": 0.84
  },
  "image:cement-plant": {
    "kind": "image",
    "src": "/media/images/cement-plant-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/cement-plant-640.avif",
        "webp": "/media/images/cement-plant-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/cement-plant-1080.avif",
        "webp": "/media/images/cement-plant-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/cement-plant-1920.avif",
        "webp": "/media/images/cement-plant-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/cement-plant-2560.avif",
        "webp": "/media/images/cement-plant-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/cement-plant-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQBACdASoVABAAPxFwsFAsJiSisAgBgCIJYwCdACHQT6A87irmF9YBAAD+jCyOPWXhx6LQvYr5Udh3Zax7tnb4X5tlSOwSSepmhLEsYV4JQnAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Cement manufacturing facility and processing structures",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 4333,
    "height": 3293,
    "scrimStrength": 0.84
  },
  "video:cement-plant": {
    "kind": "video",
    "src": "/media/images/cement-plant-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/cement-plant-poster-640.avif",
        "webp": "/media/images/cement-plant-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/cement-plant-poster-1080.avif",
        "webp": "/media/images/cement-plant-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/cement-plant-poster-1920.avif",
        "webp": "/media/images/cement-plant-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/cement-plant-poster-2560.avif",
        "webp": "/media/images/cement-plant-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/cement-plant-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 1585152,
        "mobile": true
      }
    ],
    "poster": "/media/images/cement-plant-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYAA4APxF2slEsJySisAgBgCIJYwCw7CHHHUY3O9+jjAAA/eNCJIYp3TNyup6m8DIuC9ItzIovliFjmQje+y2DXeyNiWNW+wguVRoAAAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Cement manufacturing facility and processing structures",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3840,
    "height": 2160,
    "scrimStrength": 0.82
  },
  "image:engineering": {
    "kind": "image",
    "src": "/media/images/engineering-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/engineering-640.avif",
        "webp": "/media/images/engineering-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/engineering-1080.avif",
        "webp": "/media/images/engineering-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/engineering-1920.avif",
        "webp": "/media/images/engineering-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/engineering-2560.avif",
        "webp": "/media/images/engineering-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/engineering-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoYABAAPxFyslAsJqSisAgBgCIJZQC7ABt3gA7uQSJdWupIAAD+y+XZS/c1y/Zy0m43BEKR2mrsWCX2PthTF7hfwf7lzm348umyxU8astYHVtYo4RP8EyEDMK/1DiwAAAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Industrial engineering and machine equipment",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 5233,
    "height": 3489,
    "scrimStrength": 0.83
  },
  "image:frank-mckenna-tjX_sniNzgQ-unsplash": {
    "kind": "image",
    "src": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-640.avif",
        "webp": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-1080.avif",
        "webp": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-1920.avif",
        "webp": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-2560.avif",
        "webp": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/frank-mckenna-tjX_sniNzgQ-unsplash-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoYABAAPxFysVCsJqSisAgBgCIJbACdMoHggAb5zgQ0V0NzgAD+3676Wdm3qtnQxMylFaozZ/FUHx5eg+p060DVZu7q+LHFwGHmHEe3AYrTR7Itvv3bls8LNaPNBgVBsxfkD5jFgAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Shipping containers stacked in a logistics yard",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3981,
    "height": 2595,
    "scrimStrength": 0.84
  },
  "image:haydn-n8TBTzFIRzs-unsplash": {
    "kind": "image",
    "src": "/media/images/haydn-n8TBTzFIRzs-unsplash-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/haydn-n8TBTzFIRzs-unsplash-640.avif",
        "webp": "/media/images/haydn-n8TBTzFIRzs-unsplash-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/haydn-n8TBTzFIRzs-unsplash-1080.avif",
        "webp": "/media/images/haydn-n8TBTzFIRzs-unsplash-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/haydn-n8TBTzFIRzs-unsplash-1920.avif",
        "webp": "/media/images/haydn-n8TBTzFIRzs-unsplash-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/haydn-n8TBTzFIRzs-unsplash-2560.avif",
        "webp": "/media/images/haydn-n8TBTzFIRzs-unsplash-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/haydn-n8TBTzFIRzs-unsplash-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAACQAwCdASoYABAAPxFwsFAsJiSisAgBgCIJZACdAGWawK0waMPYAP774Xz8XpUl0v7HneZrdqtaYyurKMQBq7ugF0bGU059//gcjWd8CWvUU1vvrbYAAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "haydn n8TBTzFIRzs unsplash",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 6000,
    "height": 4000,
    "scrimStrength": 0.6
  },
  "image:industrial-plant-night": {
    "kind": "image",
    "src": "/media/images/industrial-plant-night-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/industrial-plant-night-640.avif",
        "webp": "/media/images/industrial-plant-night-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/industrial-plant-night-1080.avif",
        "webp": "/media/images/industrial-plant-night-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/industrial-plant-night-1920.avif",
        "webp": "/media/images/industrial-plant-night-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/industrial-plant-night-2560.avif",
        "webp": "/media/images/industrial-plant-night-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/industrial-plant-night-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoYABAAPxF0sFCsJqSisAgBgCIJQBdgBDvzsbjvje/LEoAA/uvZHuuWwdhC/ethySlwsWvZQfdiMAVLZsDDon05ghT6om2OG0dAMT0+9WA0ZFwAAAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Industrial processing plant illuminated at night",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 6000,
    "height": 4000,
    "scrimStrength": 0.84
  },
  "video:industrial-plant-night": {
    "kind": "video",
    "src": "/media/images/industrial-plant-night-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/industrial-plant-night-poster-640.avif",
        "webp": "/media/images/industrial-plant-night-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/industrial-plant-night-poster-1080.avif",
        "webp": "/media/images/industrial-plant-night-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/industrial-plant-night-poster-1920.avif",
        "webp": "/media/images/industrial-plant-night-poster-1920.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/industrial-plant-night-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 578095,
        "mobile": true
      }
    ],
    "poster": "/media/images/industrial-plant-night-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoYAA4APxFyslAsJqSisAgBgCIJZwDA3CHe3zFd/43YAP7ugLEn+REvKDXukENjzj57omgRz2gAbjna/6xMEOAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Industrial processing plant illuminated at night",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 1920,
    "height": 1080,
    "scrimStrength": 0.76
  },
  "image:offshore": {
    "kind": "image",
    "src": "/media/images/offshore-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/offshore-640.avif",
        "webp": "/media/images/offshore-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/offshore-1080.avif",
        "webp": "/media/images/offshore-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/offshore-1920.avif",
        "webp": "/media/images/offshore-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/offshore-2560.avif",
        "webp": "/media/images/offshore-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/offshore-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAgCdASoMABAABABoJbACdAEem2efrfQ6MAD+Xxlt9zbu/dH5DaOVvc575FxYPPfnncq2pPovJuWrVQAAAA==",
    "focal": {
      "x": 0.5,
      "y": 0.46
    },
    "alt": "Small offshore structure standing above the sea",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3816,
    "height": 5096,
    "scrimStrength": 0.82
  },
  "image:offshore1": {
    "kind": "image",
    "src": "/media/images/offshore1-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/offshore1-640.avif",
        "webp": "/media/images/offshore1-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/offshore1-1080.avif",
        "webp": "/media/images/offshore1-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/offshore1-1920.avif",
        "webp": "/media/images/offshore1-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/offshore1-2560.avif",
        "webp": "/media/images/offshore1-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/offshore1-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAwCdASoVABAAPxF0sFAsJySisAgBgCIJZQAAUqLCqm1g9AD+xM7shty5mHqTF4JqfNfUPI8UFg00jLXFKEWdbh6GgAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Offshore drilling platform beside a shoreline",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 4513,
    "height": 3385,
    "scrimStrength": 0.82
  },
  "video:oil-refinery": {
    "kind": "video",
    "src": "/media/images/oil-refinery-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/oil-refinery-poster-640.avif",
        "webp": "/media/images/oil-refinery-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/oil-refinery-poster-1080.avif",
        "webp": "/media/images/oil-refinery-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/oil-refinery-poster-1920.avif",
        "webp": "/media/images/oil-refinery-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/oil-refinery-poster-2560.avif",
        "webp": "/media/images/oil-refinery-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/oil-refinery-1080.mp4",
        "type": "video/mp4",
        "width": 1920,
        "height": 1080,
        "bytes": 3090795,
        "mobile": false
      },
      {
        "src": "/media/videos/oil-refinery-1080-vp9.webm",
        "type": "video/webm",
        "width": 1920,
        "height": 1080,
        "bytes": 2924600,
        "mobile": false
      },
      {
        "src": "/media/videos/oil-refinery-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 936260,
        "mobile": true
      }
    ],
    "poster": "/media/images/oil-refinery-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAwCdASoYAA4APxFysVAsJqSisAgBgCIJYwAAW9wCLHjba5lSmAD+6+uOHV7ch+tpSCj6d0ys5lq/6DHGMwOel6/wBhxiqKZUHuqXGCrEnQyFgrpPQ38+gOtDQAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Aerial view of an illuminated oil refinery at night",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3840,
    "height": 2160,
    "scrimStrength": 0.83
  },
  "image:pexels-joseph-russo-430180075-29590119": {
    "kind": "image",
    "src": "/media/images/pexels-joseph-russo-430180075-29590119-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/pexels-joseph-russo-430180075-29590119-640.avif",
        "webp": "/media/images/pexels-joseph-russo-430180075-29590119-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/pexels-joseph-russo-430180075-29590119-1080.avif",
        "webp": "/media/images/pexels-joseph-russo-430180075-29590119-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/pexels-joseph-russo-430180075-29590119-1920.avif",
        "webp": "/media/images/pexels-joseph-russo-430180075-29590119-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/pexels-joseph-russo-430180075-29590119-2560.avif",
        "webp": "/media/images/pexels-joseph-russo-430180075-29590119-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/pexels-joseph-russo-430180075-29590119-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBACdASoYAA8APxFwsFAsJiSisAgBgCIJbACdMoACchanmKE5HOYOcwAA/r9wBtdrOogo76OZ55N+/E1yimbPDYuHpgfzUD4kmT3aNpVnwbapmNT4E3pwig3m9oII3PtchegA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Industrial processing facility illuminated at dusk",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 4967,
    "height": 3039,
    "scrimStrength": 0.79
  },
  "image:pipe-rack": {
    "kind": "image",
    "src": "/media/images/pipe-rack-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/pipe-rack-640.avif",
        "webp": "/media/images/pipe-rack-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/pipe-rack-1080.avif",
        "webp": "/media/images/pipe-rack-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/pipe-rack-1920.avif",
        "webp": "/media/images/pipe-rack-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/pipe-rack-2560.avif",
        "webp": "/media/images/pipe-rack-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/pipe-rack-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoVABAAPxF0sVAsJySisAgBgCIJYwAAUHPXHJK8wP7YOQAA/tArAGNpJqS8hN0ZhBFNiIUXIndBRwpWlunRWEEGnkRxi+YcBRTeuiWPO/PFsYsHn5XAAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Steel pipes stacked in a fabrication/storage yard",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 4032,
    "height": 3024,
    "scrimStrength": 0.82
  },
  "image:pipe-rack1": {
    "kind": "image",
    "src": "/media/images/pipe-rack1-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/pipe-rack1-640.avif",
        "webp": "/media/images/pipe-rack1-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/pipe-rack1-1080.avif",
        "webp": "/media/images/pipe-rack1-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/pipe-rack1-1920.avif",
        "webp": "/media/images/pipe-rack1-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/pipe-rack1-2560.avif",
        "webp": "/media/images/pipe-rack1-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/pipe-rack1-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQBACdASoVABAAPxF4slEsJ6SisAgBgCIJQBOkGQBgmZVKFVH4yRtgwAD93STspyWZfXj9lkqeczjJOlWUn/tO+Q0eY7hAY4LQPnB5aiibJ9eEez+kAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Stacked steel pipes beside a gantry crane",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 4032,
    "height": 3024,
    "scrimStrength": 0.81
  },
  "image:pipe-welding": {
    "kind": "image",
    "src": "/media/images/pipe-welding-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/pipe-welding-640.avif",
        "webp": "/media/images/pipe-welding-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/pipe-welding-1080.avif",
        "webp": "/media/images/pipe-welding-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/pipe-welding-1920.avif",
        "webp": "/media/images/pipe-welding-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/pipe-welding-2560.avif",
        "webp": "/media/images/pipe-welding-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/pipe-welding-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAwCdASoYABAAPxF0sVCsJqSisAgBgCIJYwCsACKlnDc2WLbUS1QAAP7cL7911TqqSwotRSwRLU/vajMvc4MfklrvRJY2ZNC8jm4Zx1WMSn30kAr0mu3EDW4AAA==",
    "focal": {
      "x": 0.56,
      "y": 0.55
    },
    "alt": "Worker welding a steel pipe, wearing protective gloves",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 5472,
    "height": 3648,
    "scrimStrength": 0.79
  },
  "video:pipeline-welding": {
    "kind": "video",
    "src": "/media/images/pipeline-welding-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/pipeline-welding-poster-640.avif",
        "webp": "/media/images/pipeline-welding-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/pipeline-welding-poster-1080.avif",
        "webp": "/media/images/pipeline-welding-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/pipeline-welding-poster-1920.avif",
        "webp": "/media/images/pipeline-welding-poster-1920.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/pipeline-welding-1080.mp4",
        "type": "video/mp4",
        "width": 1920,
        "height": 1080,
        "bytes": 2022795,
        "mobile": false
      },
      {
        "src": "/media/videos/pipeline-welding-1080-vp9.webm",
        "type": "video/webm",
        "width": 1920,
        "height": 1080,
        "bytes": 1931408,
        "mobile": false
      },
      {
        "src": "/media/videos/pipeline-welding-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 1479689,
        "mobile": true
      }
    ],
    "poster": "/media/images/pipeline-welding-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoYAA4APxFyslCsJqSisAgBgCIJagCdMoR4GB4PZka5cl/hoAD+zKbIPpu36VNfU7Pmmy5NWOepp+Rhe6j1QuKJywdvK9sKtNzjSUVrrf+eRW/JtgFJZayOn2bu4AAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Automated welding around an industrial pipe",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 1920,
    "height": 1080,
    "scrimStrength": 0.84
  },
  "image:power-plant": {
    "kind": "image",
    "src": "/media/images/power-plant-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/power-plant-640.avif",
        "webp": "/media/images/power-plant-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/power-plant-1080.avif",
        "webp": "/media/images/power-plant-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/power-plant-1920.avif",
        "webp": "/media/images/power-plant-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/power-plant-2560.avif",
        "webp": "/media/images/power-plant-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/power-plant-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAwCdASoYABAAPxF2slEsJySisAgBgCIJQBbZA8WHsq0Z/gAA3hOZI2IucQuI5LR+xU5joXAqDFGG/mdMAvaQx8PLbkdTuz22DPfvgUdRqxk9jPUjQqpvAAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Power station cooling towers releasing steam",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 7360,
    "height": 4912,
    "scrimStrength": 0.81
  },
  "video:power-plant": {
    "kind": "video",
    "src": "/media/images/power-plant-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/power-plant-poster-640.avif",
        "webp": "/media/images/power-plant-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/power-plant-poster-1080.avif",
        "webp": "/media/images/power-plant-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/power-plant-poster-1920.avif",
        "webp": "/media/images/power-plant-poster-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/power-plant-poster-2560.avif",
        "webp": "/media/images/power-plant-poster-2560.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/power-plant-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 146226,
        "mobile": true
      }
    ],
    "poster": "/media/images/power-plant-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoYAA4APxFysVAsJqSisAgBgCIJYwC7ABuYVxj3OKnW6AD2e5/rwSqHZxQ271TXAUvD63Y/HDIvxMM1WcWltz25iEYvujaAAAA=",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Power station cooling towers releasing steam",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 3840,
    "height": 2160,
    "scrimStrength": 0.84
  },
  "image:project-facilities": {
    "kind": "image",
    "src": "/media/images/project-facilities-640.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/project-facilities-640.avif",
        "webp": "/media/images/project-facilities-640.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/project-facilities-640.avif",
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAwCdASoYAA4APxF0sFAsJySisAgBgCIJbAC/OB4ahVXqdWfYyIs4AP65S9FXtbpiyGfYsmGtT+MzQ1W3z/fl1aCid1c7rv8bScczU0UAAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Illustrative facility-management graphic with a worker",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 640,
    "height": 386,
    "scrimStrength": 0.83
  },
  "image:project-management": {
    "kind": "image",
    "src": "/media/images/project-management-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/project-management-640.avif",
        "webp": "/media/images/project-management-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/project-management-1080.avif",
        "webp": "/media/images/project-management-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/project-management-1920.avif",
        "webp": "/media/images/project-management-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/project-management-2560.avif",
        "webp": "/media/images/project-management-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/project-management-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoYABAAPxF4slEsJ6SisAgBgCIJZwAASqmH+Penn2x7kAD+qMzZkIOAAobykITp82vIcoZiIvH5Z33gKGmx6ftO9tAKAAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Construction team reviewing a building worksite",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 5472,
    "height": 3648,
    "scrimStrength": 0.82
  },
  "image:scaffolding": {
    "kind": "image",
    "src": "/media/images/scaffolding-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/scaffolding-640.avif",
        "webp": "/media/images/scaffolding-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/scaffolding-1080.avif",
        "webp": "/media/images/scaffolding-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/scaffolding-1920.avif",
        "webp": "/media/images/scaffolding-1920.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/scaffolding-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRjAAAABXRUJQVlA4ICQAAACwAQCdASoKABAABABoJaQAAuWtGvwAAP7aOj/4DJqzc9sAAAA=",
    "focal": {
      "x": 0.58,
      "y": 0.5
    },
    "alt": "Residential house scaffolding (video); multi-storey building frame (photo)",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 2094,
    "height": 3486,
    "scrimStrength": 0.83
  },
  "video:scaffolding": {
    "kind": "video",
    "src": "/media/images/scaffolding-poster-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/scaffolding-poster-640.avif",
        "webp": "/media/images/scaffolding-poster-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/scaffolding-poster-1080.avif",
        "webp": "/media/images/scaffolding-poster-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/scaffolding-poster-1920.avif",
        "webp": "/media/images/scaffolding-poster-1920.webp"
      }
    ],
    "sources": [
      {
        "src": "/media/videos/scaffolding-720.mp4",
        "type": "video/mp4",
        "width": 1280,
        "height": 720,
        "bytes": 218286,
        "mobile": true
      }
    ],
    "poster": "/media/images/scaffolding-poster-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQBACdASoYAA4APxF8tFGsKCUisAgBgCIJZQDA3CFr4/KyD/gWMFfrAAD9qXNnedw7devQ3bB2RIyazL0xtjtLNdCNAj00rlz2w8/2kvv4oyU5hjBNEmBOC9JDplAAAAA=",
    "focal": {
      "x": 0.58,
      "y": 0.5
    },
    "alt": "Residential house scaffolding (video); multi-storey building frame (photo)",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 1920,
    "height": 1080,
    "scrimStrength": 0.84
  },
  "image:steel-structure-construction-1": {
    "kind": "image",
    "src": "/media/images/steel-structure-construction-1-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/steel-structure-construction-1-640.avif",
        "webp": "/media/images/steel-structure-construction-1-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/steel-structure-construction-1-1080.avif",
        "webp": "/media/images/steel-structure-construction-1-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/steel-structure-construction-1-1920.avif",
        "webp": "/media/images/steel-structure-construction-1-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/steel-structure-construction-1-2560.avif",
        "webp": "/media/images/steel-structure-construction-1-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/steel-structure-construction-1-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAwCdASoYABAAPxF4tFGsJyUisAgBgCIJZQAAW4V6votH9uWml4kQAP5RrLdRH763FKofrABbrNBqljywQNmpsBnksWZiZZKcdFocOBmfUj8q3wAAAA==",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Structural steel building framework under construction",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 6240,
    "height": 4160,
    "scrimStrength": 0.78
  },
  "image:steel-structure-construction": {
    "kind": "image",
    "src": "/media/images/steel-structure-construction-1080.avif",
    "srcset": [
      {
        "width": 640,
        "avif": "/media/images/steel-structure-construction-640.avif",
        "webp": "/media/images/steel-structure-construction-640.webp"
      },
      {
        "width": 1080,
        "avif": "/media/images/steel-structure-construction-1080.avif",
        "webp": "/media/images/steel-structure-construction-1080.webp"
      },
      {
        "width": 1920,
        "avif": "/media/images/steel-structure-construction-1920.avif",
        "webp": "/media/images/steel-structure-construction-1920.webp"
      },
      {
        "width": 2560,
        "avif": "/media/images/steel-structure-construction-2560.avif",
        "webp": "/media/images/steel-structure-construction-2560.webp"
      }
    ],
    "sources": [],
    "poster": "/media/images/steel-structure-construction-1080.avif",
    "blurDataURL": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAACwAQCdASoMABAABABoJaQAApeFAqMAAP5oCyEr5SrQDFvWtLPEAAAA",
    "focal": {
      "x": 0.5,
      "y": 0.5
    },
    "alt": "Interior of a building with structural steel roof framing",
    "credit": "User-supplied stock. Source URL, author and licence awaiting confirmation.",
    "stock": true,
    "width": 5972,
    "height": 7956,
    "scrimStrength": 0.82
  }
};
function resolve(asset:MediaAsset):MediaAsset{return {...asset,src:url(asset.src),poster:url(asset.poster),srcset:asset.srcset.map(v=>({...v,avif:url(v.avif),webp:url(v.webp)})),sources:asset.sources.map(v=>({...v,src:url(v.src)}))};}
const slots:Record<string,string> = {
  "Engineering": "image:engineering",
  "Procurement & Supply Chain": "image:Procurement-supply-chain",
  "Project Management": "image:project-management",
  "Electrical & Instrumentation": "image:Electrical & Instrumentation",
  "Project Facilities": "image:project-facilities",
  "Sectors": "video:oil-refinery",
  "Projects": "image:offshore1",
  "Insights": "image:pexels-joseph-russo-430180075-29590119",
  "Careers": "image:scaffolding",
  "Become a Vendor": "image:pipe-rack1",
  "Request a Quote": "image:cement-plant",
  "hero-1": "video:oil-refinery",
  "hero-2": "video:pipeline-welding",
  "hero-3": "video:14529100_3840_2160_30fps",
  "Oil & Gas": "image:Sectors",
  "Refining": "video:9339478-uhd_3840_2160_24fps",
  "Power": "video:power-plant",
  "Cement": "video:cement-plant",
  "refining-photo": "image:pexels-joseph-russo-430180075-29590119",
  "power-photo": "image:power-plant",
  "cement-photo": "image:cement-plant",
  "Civil & Buildings": "image:scaffolding",
  "Mechanical & Piping": "image:pipe-welding",
  "Structural Steel": "image:steel-structure-construction-1",
  "Plant Services (Turnaround & Shutdown)": "video:12966194_4096_2160_25fps",
  "Maintenance": "video:industrial-plant-night",
  "Offshore": "video:4392869-uhd_3840_2160_30fps",
  "offshore-photo": "image:offshore",
  "offshore-platform": "image:offshore1",
  "piping-yard": "image:pipe-rack",
  "piping-yard-alternate": "image:pipe-rack1",
  "mechanical-texture": "video:12966194_4096_2160_25fps",
  "civil-scaffolding-video": "video:scaffolding",
  "Plan & Procure": "image:frank-mckenna-tjX_sniNzgQ-unsplash",
  "Build & Maintain": "image:steel-structure-construction-1",
  "About": "image:industrial-plant-night",
  "Services": "image:steel-structure-construction",
  "QHSE": "image:pipe-welding",
  "Conduct": "image:pipe-rack",
  "Contact": "video:industrial-plant-night",
  "qhse-story": "video:15122253_2160_3840_30fps",
  "qhse-background": "image:industrial-plant-night",
  "cta-background": "image:offshore",
  "project-1": "image:pexels-joseph-russo-430180075-29590119",
  "project-2": "image:power-plant",
  "project-3": "image:cement-plant",
  "insight-1": "image:project-management",
  "insight-2": "video:15122253_2160_3840_30fps",
  "insight-3": "image:engineering"
};
export const placeholderMedia:MediaAsset = {"kind":"placeholder","src":"/media-placeholder.svg","srcset":[],"sources":[],"poster":"/media-placeholder.svg","blurDataURL":"","focal":{"x":0.5,"y":0.5},"alt":"Reserved media area; approved imagery needed","credit":"Placeholder; no stock asset assigned","stock":false,"width":1600,"height":1000};
export const media:Record<string,MediaAsset> = Object.fromEntries(Object.entries(slots).map(([slot,key])=>[slot,resolve(assets[key])]));
for(const slot of ["careers-people"])media[slot]=placeholderMedia;
export const heroMedia = [media['hero-1'],media['hero-2'],media['hero-3']];
export const mediaCollections:Record<string,string[]> = {
  "Mechanical & Piping": [
    "piping-yard",
    "piping-yard-alternate",
    "mechanical-texture"
  ],
  "Structural Steel": [
    "Services"
  ],
  "Civil & Buildings": [
    "civil-scaffolding-video"
  ],
  "Offshore": [
    "offshore-photo",
    "offshore-platform"
  ],
  "Refining": [
    "refining-photo"
  ],
  "Power": [
    "power-photo"
  ],
  "Cement": [
    "cement-photo"
  ]
};
